### ISSUE TITLE
Feedback and analytics

### ISSUE THREAD

**Issue by shahidhk** [google/iosched#101]
Any idea on how to configure AnalyticsManager? I have already set `ga_trackingId` in `res/xml/analytics_debug.xml` as well as `analytics_release.xml`. But cannot see any realtime reporting.

Also, what about session feebacks? Where do they go?

**Comment by PaulRashidi** [comment]
Have you rectified the issue already? 2015 source definitely provided real time analytics. We did add quite a few more comments in the code for 2015 
.
The 2015 source code has a TODO that gives you the questions/answers and allows you to code an https request to send the answers where ever you wish.

**Comment by shahidhk** [comment]
Yes! We figured out the configurations in one of the xml files. Thanks :+1: Its great to see 2015 source
