### ISSUE TITLE
Sync loop

### ISSUE THREAD

**Issue by fmendoza** [google/iosched#102]
Go to FeedbackSyncHelper.java (line 84):

``` java
cr.update(ScheduleContract.Feedback.buildFeedbackUri(sessionId), contentValues, null, null);
```

This will call

``` java
context.getContentResolver().notifyChange(uri, null);
```

in the ScheduleProvider.java and initialize another sync, making an infinite loop.

or am I wrong?

**Comment by PaulRashidi** [comment]
@tjohns Can you clarify whether this is a 2015 source issue and close or update as appropriate?
