### ISSUE TITLE
ActionBar mistake at BaseActivity

### ISSUE THREAD

**Issue by rynkowsg** [google/iosched#104]
At BaseActivity.java onCreate() method we can see those lines:

    ActionBar ab = getSupportActionBar();
        if (ab != null) {
            ab.setDisplayHomeAsUpEnabled(true);
        }

Author probably forgot that ActionBar is established (by calling setSupportActionBar()) at BaseActivity.getActionBarToolbar(). 

Mentioned lines are placed at onCreate() that is called even before onCreate() of inherited classes. So in result ab will be always equal to null, and those lines are simply redundant.

**Comment by romannurik** [comment]
This is actually intentional, in case some activities actually want to use the action bar..
