### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by tasomaniac** [google/iosched#106]
There are only 2011 and 2012 tags, can you also tag 2013 and the current version of the 2014 app on the Play Store?
The current APK on the Play Store hasn't got updated since the event.

**Comment by romannurik** [comment]
I've pushed a 2013 tag. For 2014, unfortunately I don't think we have a clean public commit representing the current version on Google Play. The master branch represents the latest and greatest 2014 code, which is what everyone should be looking at anyway.

**Comment by tasomaniac** [comment]
Thank you very much for the 2013 tag.
BTW, even if you tag the current version, I think it won't even compile
because it needs L Preview SDK which is not available anymore.

**Comment by romannurik** [comment]
We've updated the 2014 code with the final L SDK actually so it should work. Master branch

**Comment by tasomaniac** [comment]
Thank you very much.
