### ISSUE TITLE
Bug in SessionDetailActivity's background on Nexus 7

### ISSUE THREAD

**Issue by TETRA2000** [google/iosched#108]
With my Nexu7(2013) Android 5.0.1
Broken image is written in the background of SessionDetailActivity.

When I removed the line below in "values-sw600dp-v21\styles.xml", the broken image disappeared.

``` xml
<item name="android:windowElevation">16dp</item>
```

![screenshot_2015-01-07-11-35-56](https://cloud.githubusercontent.com/assets/1459450/5639892/79266360-9661-11e4-9764-c551d02bfcb4.png)

![screenshot_2015-01-07-11-55-45](https://cloud.githubusercontent.com/assets/1459450/5640078/31ac7166-9664-11e4-932b-87dfd037d4ca.png)

**Comment by JoseAlcerreca** [comment]
Obsolete
