### ISSUE TITLE
Missing style

### ISSUE THREAD

**Issue by Merguez22** [google/iosched#117]
Hi,

After import iosched in Android Studio 1.0.1, i can't rendering the fragment or others layout. The same error appear on Ubuntu 12.04 and Mac OS Yosemite. Error:

_Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references.  Couldn't find theme resource ?android:attr/paddingLeft for the current theme (282 similar errors not shown) "?android:attr/paddingLeft" in attribute "paddingStart" is not a valid format. (Edit) (166 similar errors not shown)_

**Comment by ewintory** [comment]
Hi,

I have the same issue too. Preview rendering doesn't work for the most of layouts. 
Also studio can not find the font style as it's shown below:
(Android Studio 1.1 Preview 1)

![capture-error](https://cloud.githubusercontent.com/assets/6298084/5785579/bd08745a-9df1-11e4-84ab-c87861e3f3e0.JPG)
![capture-fonts](https://cloud.githubusercontent.com/assets/6298084/5785578/bd0543f2-9df1-11e4-8b83-4fbfb7f86a9b.JPG)

**Comment by jenzz** [comment]
@ewintory That's just the IDE complaining about the `android:textStyle` attribute which is supposed to hold a flag (`bold`, `italic` or `normal`) as its value and we're giving it a reference to one of those flags (`@integer/font_textStyle_medium`) which works fine as well. You can safely ignore that by adding `<!--suppress AndroidDomInspection -->` above that `TextView`.

**Comment by gagaJay** [comment]
I have exactly the same problem as Merguez22.

My Android Studio version is 1.0.2

Can someone please help us out?

**Comment by Macs75** [comment]
what about "?android:attr/paddingLeft" reference in values-v17/styles.xml
android studio seems not to get it.

"?android:attr/paddingLeft" in attribute "paddingStart" is not a valid format. (Edit) (122 similar errors not shown)

**Comment by ipalermo** [comment]
Any solution to this issue??

**Comment by renangueiros** [comment]
I managed to solve this problem going in the archive `Android/res/values/styles.xml (v17)`, commenting entire file or deleting the same.

I hope it helps those who have the same questions .

**Comment by JeffersonRSM** [comment]
Thanks you renangueiros, your answer solved my problem.

**Comment by JoseAlcerreca** [comment]
Obsolete
