### ISSUE TITLE
Android Studio fails to build project

### ISSUE THREAD

**Issue by Gnafu** [google/iosched#12]
Following the BULDING.txt file instructions, Android Studio fails to build the project with the message:

Task 'assemble' not found in root project 'iosched'.

The "Gradle tasks" list is empty in Android Studio

**Comment by NiteenR** [comment]
iam geting error like as follow 

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\nitin\AndroidStudioProjects\iosched-master\settings.gradle' line: 17

* What went wrong:
A problem occurred evaluating root project 'iosched-master'.
> Could not find method include() for arguments [:android] on root project 'iosched-master'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.505 secs
Disconnected from the target VM, address: '127.0.0.1:59280', transport: 'socket'

Process finished with exit code 1
