### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by NiteenR** [google/iosched#126]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\.....\AndroidStudioProjects\iosched-master\settings.gradle' line: 17

* What went wrong:
A problem occurred evaluating root project 'iosched-master'.
> Could not find method include() for arguments [:android] on root project 'iosched-master'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.505 secs
Disconnected from the target VM, address: '127.0.0.1:59280', transport: 'socket'

Process finished with exit code 1

**Comment by PaulRashidi** [comment]
Which version of Studio were you using?
