### ISSUE TITLE
BasicHttpClient outdated

### ISSUE THREAD

**Issue by IgorGanapolsky** [google/iosched#128]
Why are you using TurboManage BasicHttpClient?  I mean this is such an outdated library.  You can use Android's default HttpClient, or use Volley!  

Please explain,
Thanks,
Igor

**Comment by iNoles** [comment]
Somebody else would have to said "Why not Okhttp?" too

**Comment by IgorGanapolsky** [comment]
That would be fine as well.  I just don't get why we have to use outdated and irrelevant libraries.  Especially when budding developers will look at this code and misconstrue it as the de facto standard.

**Comment by PaulRashidi** [comment]
Thanks, we'll look into this.

**Comment by JoseAlcerreca** [comment]
Obsolete
