### ISSUE TITLE
choose between AsyncTask and IntentService/AsyncTaskLoader

### ISSUE THREAD

**Issue by yulin2** [google/iosched#129]
Hello, I'm doing research on Android async programming. I see in `iosched`, you use `IntentService`  at some places (such as `SessionCalendarService`) while use `AsyncTask` at other places (such as in `NfcBadgeActivity`). I'm wondering how do you choose between `AsyncTask` and `IntentService`? because both are used to execute background tasks.

As far as I know, some articles (for example [this article](http://bon-app-etit.blogspot.com/2013/04/the-dark-side-of-asynctask.html)) mention that AsyncTask leads to memory leak and losing task result when there's a configuration change (such as orientation change). But using `IntentService` or `AsyncTaskLoader` can avoid such problems.

**Comment by PaulRashidi** [comment]
This is on our radar.

**Comment by PaulRashidi** [comment]
AsyncTask CAN (not WILL) lead to memory leaks. Any other anonymous class or reference to an activity instance in code that survives the activity lifecycle can cause an leaks as well. There is no perfect answer as it depends on what you're doing and gets a little more complicated if you are also using Fragments or consider the other async paradigms. If your async code is cheap and can be redone on a rotation then it's probably OK for an AsyncTask if you cancel in onStop(). If it's not cheap then you probably need IntentService (or Service).

**Comment by iNoles** [comment]
@PaulRashidi That is why, I am waiting for Android supports lambdas which is like static methods that wouldn't have a reference to the parent class.

**Comment by chiaramail** [comment]
I prefer using the Volley library for async communications, especially when talking to a RESTful service that's returning JSON data.

**Comment by yishai-glide** [comment]
Context leaks in AsyncTasks are done when there is a Context in it or any other member of the surrounding class (usually activity or fragment), I suspect they wanted, at the time, to have as less 3rd party libraries as possible and they considered Volley as one.
