### ISSUE TITLE
Sliding Tab Layout Issue with landscape mode 

### ISSUE THREAD

**Issue by wakka1889** [google/iosched#130]
When i use landscape mode with my app, the Sliding Tab Layout doesn't work any more, everything about the tab is stuck. I hope that you can help me. thank you

**Comment by PaulRashidi** [comment]
Could you be a little more specific if you're still experiencing this issue?

**Comment by rox117** [comment]
have similar problem.. only the first tab title is diaplyed and the indicator disappears
![unnamed](https://cloud.githubusercontent.com/assets/8076406/8817743/ecfc5a6c-2ffc-11e5-82a6-7522daefccc9.jpg)

**Comment by JoseAlcerreca** [comment]
Obsolete
