### ISSUE TITLE
I/O 2015 Source Code

### ISSUE THREAD

**Issue by intelliot** [google/iosched#139]
Where's the I/O 2015 app?

(Update: Yes, I'm referring to the source code)

**Comment by NashLegend** [comment]
项目简介上不就有么
https://play.google.com/store/apps/details?id=com.google.samples.apps.iosched

**Comment by asbadve** [comment]
He is talking  about the code

**Comment by LOG-TAG** [comment]
That is what we are all waiting for :+1:  

before that slowly we can complete this Home work  https://github.com/chrisbanes/cheesesquare

**Comment by PaulRashidi** [comment]
Hi, 2015 source isn't yet available. Rest assured that we are working on it.

**Comment by Proximator** [comment]
Thanks for the update.
Do you know approximately when it will be available ?

**Comment by Freedom000** [comment]
Well，I think the app is open-source.

**Comment by NashLegend** [comment]
Maybe next month

**Comment by timrae** [comment]
Yes preeeeease, the source code for this is pedagogically important for the Android community

**Comment by KevinMisfit** [comment]
@timrae 
yes, indeed :+1:

**Comment by httvncoder** [comment]
Sourc expect more interesting next time.!!wait

**Comment by sevar83** [comment]
Come on, it's already time for IO 2016!

**Comment by mananwason** [comment]
Hey guys, It's been days now. Please release the source !!

**Comment by hegazy** [comment]
@PaulRashidi We have rested for 38 days now.

**Comment by hugonardo** [comment]
![WANT!](http://vignette3.wikia.nocookie.net/xenoblade/images/c/c9/Want.gif/revision/latest?cb=20150503133839)

**Comment by hesling** [comment]
![Uploading QQ图片20150709155356.gif…]()

**Comment by halfbaked** [comment]
any idea when the 2015 source will be released? Is there that much proprietary code in it, or there is a lot of clean up to make it presentable to the public?

**Comment by CNadam** [comment]
hoping earlier!

**Comment by IgorGanapolsky** [comment]
Why hasn't the iosched 2015 been released yet?  The year 2015 is half-way over already!

**Comment by PaulRashidi** [comment]
We know you won't let us forget. We are working on it still. If you have specific questions about how we did something let me know and I'll share the info in the mean time.

Thanks

**Comment by IgorGanapolsky** [comment]
I am specifically interested in the unit testing aspect of this project.
Things like MockWebServer, MockResponse, etc - which do integration testing
of restful APIs.

Thanks,
Igor

**Comment by PaulRashidi** [comment]
We removed the use of the Google REST-based APIs in the app in 2015. File an issue on this repo (https://github.com/googlesamples/android-testing) asking if there is a good sample available. The team that monitors that sample might have something.

**Comment by IgorGanapolsky** [comment]
If you removed Google rest APIs, does that mean you aren't using REST
endpoints in the app?

**Comment by PaulRashidi** [comment]
Sorry, I translated that a little wrong on my side. We removed the use of https://developers.google.com/api-client-library/java/google-api-java-client/android this year. We still have  a server component. I assumed you wanted to see how to use the MockWebServer and MockResponse to for the Google REST calls which may or may not have been the case. It's still probably best to request this type of sample on that other repo.

**Comment by nachtien** [comment]
@PaulRashidi, I'm really curious how the network layer is architected in the 2015 app.  Is there anyway you can describe or give any insight how it's implemented? I'm really excited to see how it was built.

**Comment by nachtien** [comment]
Also, did you guys ever consider using MVP or MVVM patterns in any of the apps that you have worked on at ~~Google~~ Alphabet?

**Comment by IgorGanapolsky** [comment]
Looks like we may get iosched2015 by 2016 :)

**Comment by FabianTerhorst** [comment]
Does the Google io 2015 APP has a application structure like https://events.google.com/io2015/schedule?sid=358c9f91-b6d4-e411-b87f-00155d5066d7 ?

**Comment by halfbaked** [comment]
it would be great to see a good/correct example of a recyclerview with dynamic subheaders

**Comment by hesling** [comment]
<a href="https://github.com/cymcsg/UltimateRecyclerView">here is the example</a>, hope you like it

**Comment by PaulRashidi** [comment]
@Nick: Nothing fancy happening with networking although we are continuing
to use glide.
@Igor: We have considered those patterns. More on that later.
@Fabian: not really as that's a web app and IOSched is written as an
Android native app.
@halfbaked: You should request that sample on the existing RecyclerView
sample on GitHub as an issue and I'll talk to the person who maintains it.

Paul Rashidi | Developer Programs Engineer | paulrashidi@google.com |
 818-5DE-VREL

**Comment by nachtien** [comment]
Thanks.  I'm looking forward to see what you guys have done.

**Comment by halfbaked** [comment]
@PaulRashidi thanks for the response. I've created the issue https://github.com/googlesamples/android-RecyclerView/issues/9

**Comment by c0nnector** [comment]
Hey guys don't worry. I'm sure they will relase the code soon(TM)
![1597272](https://cloud.githubusercontent.com/assets/2115575/9543261/30c53714-4d80-11e5-8756-ec50217c8334.jpg)

**Comment by schembad** [comment]
@nachtien had a very good point. When is Google going to invest a bit of time laying out some good architectural practices such as MVP without ending up using Dagger and EvenBus?

**Comment by IgorGanapolsky** [comment]
@nachtien. There is absolutely nothing wrong with using Dagger!  Dagger is
a perfect tool to complement MVP architecture.

**Comment by schembad** [comment]
Nobody has said that there's something wrong with Dagger. But I'd personally prefer a platform that natively enables devs to implement a clean architecture without relying on 3rd-party libraries. I actually think that should be a given.

**Comment by IgorGanapolsky** [comment]
Dude, Dagger2 is dependency injection.  It is actually being developed by
Google now.  So excuse me if I don't understand what you mean by "replying
on 3rd party libraries".

**Comment by epiphany27** [comment]
@IgorGanapolsky 
Official android guidelines clearly states that - "avoid dependency injection frameworks" like Guice or RoboGuice, though it doesn't mention Dagger anywhere. Link: https://developer.android.com/training/articles/memory.html#DependencyInjection. 
Hence, I never bothered about using Dagger in my projects.

**Comment by shmuelr** [comment]
@epiphany27 

See this - https://blog.gouline.net/2015/05/04/dagger-2-even-sharper-less-square/
(and this https://www.youtube.com/watch?v=oK_XtfXPkqw)

Dagger2 does not use refection. It simply generates the code at compile time. Because of this it does not have the overhead normally associated with dependency injection.

**Comment by epiphany27** [comment]
@shmuelr 
That's fantastic :-). Thanks a ton!

**Comment by IgorGanapolsky** [comment]
epiphany27. It is very unfortunate that you have been so grossly misled and
are missing out on one of the most popular tools for today's Android
development.  Dagger was created as a response to those shortcomings in
Guice that you mentioned.  It creates an object graph at compile time so it
has no performance penalties.  And Google themselves are developing Dagger2
now!  It is sad that people have to read these stupid Android guidelines
and be misled...

**Comment by halfbaked** [comment]
The plight of Syrian refugees is sad, not using a dependency injection
library is simply a choice.
Relax Igor. Take a holiday, and some perspective. Your opinion is simply
that - your opinion.

**Comment by IgorGanapolsky** [comment]
@halfbaked. Not a choice sonn.  Ignorance.

**Comment by Turbo87** [comment]
@PaulRashidi why are you not just developing the missing parts of the app in the open? that way we could at least have a look at the current state. what is currently happening here is not quite what my definition of "open source" means...

**Comment by perpetuatingcuriosity** [comment]
@PaulRashidi I noticed a change in the back/up navigation from 2014/2015, i.e.:

In iosched 2015, if you navigate back/up from any activity that isn’t “Explore”, it will take you back to the “Explore” activity as opposed to 2014, where a similar action would exit the app.

How is this achieved? I thought maybe the Explore activity was the parent activity to the others, but I haven’t been able to duplicate this effect. 

Any tips?

**Comment by IgorGanapolsky** [comment]
@perpetuatingcuriosity In io2014 we didn't have a Toolbar.  It is now
possible with the Toolbar.

**Comment by perpetuatingcuriosity** [comment]
@IgorGanapolsky Can you elaborate a bit? Is it just a Intent to start the Explore activity?

**Comment by hzsweers** [comment]
@PaulRashidi you're on target to miss the release of the OS that this app is supposed to serve an example for. I understand you're updating the app to better prepare for that, but last year that was done iteratively with public updates to the repo. It was a win-win situation since developers could follow along and Google was able to get feedback on what their pain points were. Why change that?

**Comment by perpetuatingcuriosity** [comment]
@PaulRashidi I really appreciate you taking the time to answer I/O 2015 questions in this issue. Any thoughts on my previous question? :

“In iosched 2015, if you navigate back/up from any activity that isn’t “Explore”, it will take you back to the “Explore” activity as opposed to 2014, where a similar action would exit the app.

How is this achieved? I thought maybe the Explore activity was the parent activity to the others, but I haven’t been able to duplicate this effect.”

If it is the toolbar, as @IgorGanapolsky mentioned, can you elaborate on how you used the toolbar to achieve this? I just restructured my app and this is an issue I’m having trouble solving.

At the moment I’m using a BaseActivity as in iosched 2014, and overriding onBackPressed to check if the activity is an instance of my MainActivity, if it isn’t I start a new intent to my MainActivity. This doesn’t seem like the best way to achieve this.

Would you be able to point me in the right direction?

**Comment by hesling** [comment]
<B>WHO</B> says "Source code for the app will be available soon after I/O" ?

**Comment by powder366** [comment]
Also waiting:-)

**Comment by Master-Wang** [comment]
I told my son, when the source code released,  fork it on my grave ...

**Comment by enzokie** [comment]
@Master-Wang  I added it in will.

**Comment by agent10** [comment]
What's the problem to release alpha version of source code and then continue improving it with community help?

**Comment by qqli007** [comment]
Please show it.

**Comment by haogefeifei** [comment]
- -  2015-09-22

**Comment by VihaanVerma89** [comment]
we are waiting for it :\

**Comment by perchi** [comment]
+1

**Comment by lawloretienne** [comment]
I'm curious how the searchview widget was implemented in this app.  Hopefully the source code is released soon.

**Comment by hzsweers** [comment]
It's been over a month since this thread was last acknowledged by a maintainer. This is ridiculous.

**Comment by oscarmakala** [comment]
By the time the source code is out. it will be google io 2016.

**Comment by febinsathar** [comment]
+1

**Comment by rock3r** [comment]
Guys, it would be great if you could stop asking for the iosched 2015 source code. IF and WHEN it'll be ready for release, you'll get it. Asking every other day or +1 won't get us any closer to getting the sources -- if, again, they'll ever be released. So please respect others and stop spamming everyone.

**Comment by hesling** [comment]
@rock3r hi, man, take it easy, just kidding

**Comment by ronanhardiman** [comment]
@hesling  just kidding

**Comment by mingfai** [comment]
+1. I'd like to see an example of how Google implement the search "filter" overlay that is triggered by the upper right button. It is a new pattern. 

I subscribed to this thread from the very beginning and didn't post anything. Only until I see @rock3r 's message, I'd like to say who view those "+1" as spam should unsubscribe from this issue, and use another way to monitor (e.g. Google alert) or come back to check from time to time. People post messages for a reason. And I don't see anyone is intended to spam.

**Comment by kyleinfo** [comment]
still waiting

**Comment by AlexanderGarmash** [comment]
Guys from Google. We are still waiting app...
![x_607a00b3](https://cloud.githubusercontent.com/assets/2606047/10197544/db616ef6-67a0-11e5-97e9-1652693a674a.jpg)

**Comment by gubaozhen** [comment]
waiting for the google io 2015!!!!

**Comment by mpopag** [comment]
meh skip it, let's wait for 2016 :))

**Comment by vipinhelloindia** [comment]
meh skip it, let's wait for 2016 :)) +1

**Comment by halfbaked** [comment]
do the right thing?

**Comment by hesling** [comment]
@halfbaked I~~ feel something so wrong, but Doing the right thing.

**Comment by linuxbelletian** [comment]
we need more patient

**Comment by Loyea** [comment]
mark.

**Comment by Loyea** [comment]
https://play.google.com/store/apps/details?id=com.google.samples.apps.iosched&hl=en

The official Google I/O 2015 app was built to be your co-pilot to navigate the conference, whether you’re attending in-person or remotely.
-- Explore the conference agenda, with details on themes, topics and speakers
-- Add events to a personalized schedule
-- Get reminders before events in “My schedule” start
-- Watch the keynote and sessions live stream
-- Sync your schedule between all of your devices and the I/O website
-- Guide yourself using the vector-based conference map
-- Follow public social I/O related conversations on Google+ and Twitter
-- See I/O content from previous years in the Video screen
-- Use the Widget to check your upcoming events directly from your home screen
*Exclusive for In person attendees:*
-- Take advantage of facilitated pre-event WiFi configuration

This app is optimized for phones and tablets of all shapes and sizes.
####Source code for the app will be available soon after I/O.

**Comment by PaulRashidi** [comment]
Initial source posted. We'll be iterating on it a bit going forward. As always we welcome contributions.

**Comment by YousufSohail** [comment]
![56923803](https://cloud.githubusercontent.com/assets/2059838/10479022/d2f9b090-727a-11e5-96aa-b92347fe83f2.jpg)

**Comment by snakemouse3d** [comment]
Thank you very much. Cloning.............. :dancers:

**Comment by Loyea** [comment]
OH MY GOD!

**Comment by oderayi** [comment]
YESSSSS!!!!

**Comment by KevinMisfit** [comment]
Finally , thank you google!!!:))

**Comment by tolis764** [comment]
Great!!

**Comment by LOG-TAG** [comment]
disappointed to know that 2015 app doesn't use the data binding library.

**Comment by BillBosiolis** [comment]
Just had a quick check...Presenters? Unit Tests?

It's good to see these additions

**Comment by lawloretienne** [comment]
Where is the link to the repo?
