### ISSUE TITLE
how to use customview of tabs with slidingTablayout i want two textviews in vertical orientation ? 

### ISSUE THREAD

**Issue by engr-erum** [google/iosched#146]
i have done  this  : 
slidingTabLayout.setCustomTabView(R.layout.layout_custom_tabs,R.id.textview_customprofiletabtext);

but still i m getting single title textview  instead of two textviews in vertical orientation ? 

http://imgur.com/9ekZ4qc

**Comment by JoseAlcerreca** [comment]
Obsolete
