### ISSUE TITLE
[IO 2015] SessionDetailFragment initViews() practice

### ISSUE THREAD

**Issue by eneim** [google/iosched#151]
It seems that the way to retrieve component views of this Fragment (so sorry I'm reading this class only) doesn't seem to be a good practice. I personally consider it a bad way.

Specific: calling `Activity#findViewById(int)` from inside a Fragment instead of `View#findViewById(int)` in `SessionDetailFragment#initViews()`. I guess an `initViews(View root)` should be the proper way to go, and of course, this method will be called inside `Fragment#onViewCreated(View, Bundle)`. Well, let us make the source code better!

**Comment by k0shk0sh** [comment]
how about if the view is not inside the fragment layout? but in the activity layout? i don't see any bad practice about it tho, as the fragment is within the activity so it should be okay. if the view is inside the fragment then i 100% support your opinion.

**Comment by PaulRashidi** [comment]
getView() does seem to be the better approach here at first glance. @freewheelnat, it looks like you updated this code a bit last, could you advise?

**Comment by k0shk0sh** [comment]
@PaulRashidi, calling getView() for a view that present in the layout inflated in the fragment should cause no problem as long as you call it after onViewCreate/d. as i mentioned if the view isn't within the fragment layout then calling getActivity().findViewById should be no problem. correct me if im wrong.

**Comment by PaulRashidi** [comment]
@k0shk0sh I think you're saying you want a Fragment to access views in other fragments or the parent activity. While this is possible, it's generally not the best approach as it makes the code a little bit brittle. In very complex hierarchies or ones with duplicates IDs (think duplicate fragments) it can introduce performance or logic problems as well.

https://developer.android.com/training/basics/fragments/communicating.html

**Comment by eneim** [comment]
@k0shk0sh Generally a Fragment can be attached to any Activities, so you could not guarantee that your Fragment **knows** about its host Activity. Furthermore, latest support library suggest that your ```android.support.v4.app.Fragment``` could be attached to any Context holder host (so the **Host** might not be an Activity. A good practice for this is not out there, but yeah they have reason for deprecating the current familiar ```Fragment#onAttached(Activity)```), so I think you should take a good care of your practices. I agree that ```getView()``` instead of ```getActivity()``` looks good at first, since we know that this Fragment has a proper View (not null).

**Comment by k0shk0sh** [comment]
thanks guys for the explanation, however you didn't get my point, as i pointed out in my first comment, i did say if the view is presenting within the fragment then calling getActivity().findViewbyId is bad practice, but in some cases calling a view that is presenting in the activity view shouldn't be bad as long as you know what are you doing. i can't see any bad reason about as long as you know what are you doing :D . btw for the fragment Context i haven't tried it yet but it doesn't seem to play very well.

**Comment by eneim** [comment]
@k0shk0sh as @PaulRashidi mentions, it could work on simple implementation though, since you are able to read and maintain the whole class. But when you turn to a bigger concept, you may got headache instead :D. And in my opinion, the concept of Fragment would suggest you to always use its ```getView()``` instead of ```getActivity()```: a Fragment is a piece of UI (well, modern Fragment can have no View) which is supposed to be attached and detached from Windows. So for more flexibility, and correctness, I would consider to used the Fragment's view to do the rest. But yeah I agree that which is working, and stable, we keep it ;).

**Comment by freewheelnat** [comment]
Agreed with comments here as in this instance, the Fragment has a View and we are calling views within that View so we should use getView() instead of getActivity().

**Comment by JoseAlcerreca** [comment]
Obsolete
