### ISSUE TITLE
[ASK] Remove sensitive infor from Pull request

### ISSUE THREAD

**Issue by eneim** [google/iosched#169]
It's kind of github beginner question, and maybe out of topic, so pardon me. I want to ask what should be the best way to commit/create pull request to this project without showing my keys (specified in gralde.properties).

Thanks in advance.

**Comment by elmargomezio** [comment]
what about .gitignore?

**Comment by eneim** [comment]
It requires my gitignore is merge with this project first, which is not a good solution, since I need to add gradle.properties to gitignore, but yet that's not what they want to do. You guys need to see that file actually :D.

I have a research [here](https://help.github.com/articles/remove-sensitive-data/), but it ends up with the fact that I still need to add the file to .gitignore, which is not supposed as above.

**Comment by ardock** [comment]
**Modules build.gradle**
```
    signingConfigs {
        debug {
            storeFile file(rootProject.ext.androidDebugStoreFile)
            storePassword rootProject.ext.androidDebugStorePassword
            keyAlias rootProject.ext.androidDebugKeyAlias
            keyPassword rootProject.ext.androidDebugKeyPassword
        }
        release {
            storeFile file(rootProject.ext.androidReleaseStoreFile)
            storePassword rootProject.ext.androidReleaseStorePassword
            keyAlias rootProject.ext.androidReleaseKeyAlias
            keyPassword rootProject.ext.androidReleaseKeyPassword
        }
    }
```
**Main project build.gradle**
```
// Control Android properties of all your modules from the main project.
// See Tip 1: http://tools.android.com/tech-docs/new-build-system/tips
// Parameterise values so they can be overridden by environment level or command line properties.
// See gradle.properties file for more information on the overriding system and the custom values.
project.ext {
    androidDebugStoreFile = ANDROID_DEBUG_STORE_FILE
    androidDebugStorePassword = ANDROID_DEBUG_STORE_PASSWORD
    androidDebugKeyAlias = ANDROID_DEBUG_KEY_ALIAS
    androidDebugKeyPassword = ANDROID_DEBUG_KEY_PASSWORD

    androidReleaseStoreFile = ANDROID_RELEASE_STORE_FILE
    androidReleaseStorePassword = ANDROID_RELEASE_STORE_PASSWORD
    androidReleaseKeyAlias = ANDROID_RELEASE_KEY_ALIAS
    androidReleaseKeyPassword = ANDROID_RELEASE_KEY_PASSWORD
}
```

**gradle.properties** 

```
# The store file location is relative to the module base, and so needs to go
# up one level of the directory hierarchy to get to the project root.
ANDROID_DEBUG_STORE_FILE=../android/debug.keystore
ANDROID_DEBUG_STORE_PASSWORD=android
ANDROID_DEBUG_KEY_ALIAS=androiddebugkey
ANDROID_DEBUG_KEY_PASSWORD=android
ANDROID_RELEASE_STORE_FILE=../android/debug.keystore
ANDROID_RELEASE_STORE_PASSWORD=android
ANDROID_RELEASE_KEY_ALIAS=androiddebugkey
ANDROID_RELEASE_KEY_PASSWORD=android
```

[Configuring the build environment via gradle.properties](https://docs.gradle.org/current/userguide/build_environment.html)

> The configuration is applied in following order (if an option is configured in multiple locations the last one wins):

> from gradle.properties in project build dir.
> from gradle.properties in gradle user home.
> from system properties, e.g. when -Dsome.property is set on the command line.

Part of this is from the 2014 version and my experiments [here](https://github.com/ardock/iosched/tree/ttt-cache-as1-rc2) learning travis-ci.

 I didn't try the last step, I used two different forks (one for me and one for contribute back) but I understand that it's possible to override the shared gradle.properties using your gradle user home values.

This was another reason to disagree with the deletion of the signingConfigs the other day that you explained my point of view.

Residual configuration remains [here](https://github.com/google/iosched/blob/master/gradle.properties)

```
# The store file location is relative to the module base, and so needs to go
# up one level of the directory hierarchy to get to the project root.
iosched14_android_debugkey_storefile = ../android/debug.keystore
iosched14_android_debugkey_storePassword = android
iosched14_android_debugkey_keyAlias = androiddebugkey
iosched14_android_debugkey_keyPassword = android

iosched14_android_releasekey_storefile = ../android/debug.keystore
iosched14_android_releasekey_storePassword = android
iosched14_android_releasekey_keyAlias = androiddebugkey
iosched14_android_releasekey_keyPassword = android
```

**Comment by eneim** [comment]
Thank @ardock . This really get the point out of me. So I think I would merge the current iosched's gradle.properties to my home gradle setting, so that it would read my global setting instead. And I don't need to modify project's properties file. I will try that solution.

**Comment by eneim** [comment]
@ardock I tried and it works. I have some minor improvement in gradle.properties which I would like a review. I will close this issue here. Thanks again for your help.

**Comment by ardock** [comment]
@eneim you are welcome, I'm glad it worked.
