### ISSUE TITLE
SlidingTabLayout not scrolling

### ISSUE THREAD

**Issue by pupaxxo** [google/iosched#171]
Hi! I'm using SlidingTabLayout and when i set DistributeEvenly on true I get this (not always, only on a few devices like the nexus 5 with default dpi):
![schermata 2015-11-30 alle 20 27 58](https://cloud.githubusercontent.com/assets/2815664/11482143/73dd63e4-97a1-11e5-9652-18a95f7ac2a2.png)

**Comment by JoseAlcerreca** [comment]
Obsolete
