### ISSUE TITLE
Syntax of compile gradle statements causing problems for Android Studio 1.5.1.

### ISSUE THREAD

**Issue by GitTom** [google/iosched#179]
I'm using the current stable Android Studio v1.5.1 on Windows.

When ever I do something that causes AS to update the Android modules' build.gradle it runs compile statements together - breaking the file.  

I then manually split the statements and it works fine again, so it isn't really a problem for me now, but I still think it is worth noting.  I'm a gradle newbie - maybe there is a slight change in syntax that would prevent this from happening?

The statements that are affected are compile statements that use gradle properties, starting [here](https://github.com/google/iosched/blob/master/android/build.gradle#L133).

**Comment by PaulRashidi** [comment]
"causes AS to update the Android modules' build.gradle" = Use the Project Explorer to edit project properties in those files?

**Comment by GitTom** [comment]
It last happened when I added a new flavor to the project via the 'project structure' dialog.

I think it happens anytime I use any feature of AS that causes it to re-write the build.gradle file.

Thinking about why it happens to me and not others (I assume), maybe it has something to do with the combintation of those statements and line-endings on Windows?

**Comment by PaulRashidi** [comment]
Thanks. I'll look into it.

**Comment by JoseAlcerreca** [comment]
Obsolete
