### ISSUE TITLE
Minor error in server-side setup instructions - YOUTUBE_API_KEY moved

### ISSUE THREAD

**Issue by GitTom** [google/iosched#180]
The [instructions here](https://github.com/google/iosched/blob/master/doc/BUILDING.md) for server-side setup include this line:

"8. Enter your API key in the YOUTUBE_API_KEY constant in Config.java"

This should instead refer to gradle.properties [file here](https://github.com/google/iosched/blob/master/gradle.properties#L63).

**Comment by JoseAlcerreca** [comment]
Obsolete
