### ISSUE TITLE
Crash  explore list  view

### ISSUE THREAD

**Issue by dubu** [google/iosched#182]
crash message

```
Caused by: java.lang.RuntimeException: bad array lengths at android.os.Parcel.readStringArray(Parcel.java   
...
explore.TagFilterHolder$1.createFromParcel
```

when come back to app
some time crash  at explore list 

![io15_1](https://cloud.githubusercontent.com/assets/2464016/13115438/2a85c556-d5db-11e5-9010-e866a6697970.png)
![io15_2](https://cloud.githubusercontent.com/assets/2464016/13115439/2a888ec6-d5db-11e5-8245-6f95e1905674.png)

**Comment by PaulRashidi** [comment]
The solution to this bug was fixing the Parcelable implementation in TagFilterHolder. It was incorrectly trying to read array information twice. We've fixed this in 2016 source.

            String[] filters = in.createStringArray();
            in.readStringArray(filters);
...
            int[] categories = in.createIntArray();
            in.readIntArray(categories);
