### ISSUE TITLE
Hard to use Presenter pattern

### ISSUE THREAD

**Issue by oderayi** [google/iosched#188]
I'm having a hard time navigating and understanding the Presenter pattern. Turns out I'm not alone, 

https://www.reddit.com/r/programming/comments/3os2lg/google_releases_google_io_showcase_apps_huge_lump/

I do have some experience with the MVP pattern, but what I can see in iosched is way too complex that I'm thinking of avoiding it entirely.

I am basically trying to add a new "module" with it's activity, fragment, model and model data. How the whole fit together from the addPresenterFragment(...) is not clear. How do actions lead to database reads and writes is also very fuzzy.

Any guidance will be appreciated.

**Comment by tasomaniac** [comment]
You know that this place is not for guidance, right?

**Comment by PaulRashidi** [comment]
@oderayi Is your request that the MVP as IOSched use it be more clear or are you using the project to generally learn MVP? This would be the appropriate place to report the former, but not the latter. That being said, I think we may have some updates in how it's documented this year to make it more clear going forward.

**Comment by P-Hill** [comment]
It was a comment on the docs or its usability.
Thanks,
-paul
