### ISSUE TITLE
Can you open source the script that updates images in the cloud storage bucket.

### ISSUE THREAD

**Issue by pengliaoye** [google/iosched#191]
what's the Bash script content

**Comment by PaulRashidi** [comment]
We'll look into open sourcing this in the 2016 source.

**Comment by Danica99** [comment]
I needed open archives and manage

**Comment by Soulcyber** [comment]
@PaulRashidi  when the 2016 source will be published? 
Thanks :)

**Comment by PaulRashidi** [comment]
I can't make any promises, but our planning has us releasing it much sooner this year.

Please do not respond with +/-1s or similar comments as many people subscribe to this project.

**Comment by Soulcyber** [comment]
Glad to hear that.
Good work

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
