### ISSUE TITLE
Documentation which explain how whole app works

### ISSUE THREAD

**Issue by viz-prakash** [google/iosched#193]
It would be great help if there will be a document which explains how the components work, both android and server. There are few document which explains some part of app but not everything in it. It takes lot of effort, in terms of time, to understand the whole functioning of app.

**Comment by shailen** [comment]
I agree. We'll try to add the requested documentation for the 2017 app.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
