### ISSUE TITLE
paper-drawer menu items not showing 

### ISSUE THREAD

**Issue by dman777** [google/iosched#194]
![pic2](https://cloud.githubusercontent.com/assets/887815/15077992/a9b69bec-1376-11e6-9051-918bc5c34e8e.jpg)

```
four@localhost ~ $ google-chrome-stable --version
Google Chrome 50.0.2661.86 
```

**Comment by PaulRashidi** [comment]
I've sent an email to the team that works on the website, but closing this issue since this issue tracks the Android app and not the website.

**Comment by ebidel** [comment]
This is the 2015, which has become busted in a year's time :\ Can you file a bug at github.com/GoogleChrome/ioweb2015?

**Comment by dman777** [comment]
Sure, no problem :+1:  [Please see #1539](https://github.com/GoogleChrome/ioweb2015/issues/1539)
