### ISSUE TITLE
Dutch Translation 

### ISSUE THREAD

**Issue by abdelouali** [google/iosched#198]
Hello, 

Is it possible for me to contribute to this project?
I could translate all the files in values to Dutch. I saw that there is not a values-nl directory available? May I translate the files and do a PR?

Best regards,

**Comment by Ch3ck** [comment]
Well that's why this project is open source @abdelouali. Feel free!

**Comment by PaulRashidi** [comment]
We'd definitely look at the PR, but please don't expect it to be reviewed until a few weeks after I/O.

**Comment by PaulRashidi** [comment]
Also, just so you know, the legal and conduct files need to go through some reviews on our side. Were you planning on doing the first translation of those files and do you have experience wth formal translations for things like that?
