### ISSUE TITLE
Regarding source code for 2016 I/O app

### ISSUE THREAD

**Issue by Vinayrraj** [google/iosched#199]
Paul, by when source code of I/O 2016 app be published?

**Comment by murtaza-webdev** [comment]
Please release earlier and if possible bit improve documentation with structure and/or architecture of application.

**Comment by fernandomantoan** [comment]
https://github.com/google/iosched/issues/191#issuecomment-217194714

**Comment by PaulRashidi** [comment]
I don't have a date but we are actively working on it. 

Please do not '+1' or continue asking daily on this or other issues in the repo. Many people subscribe to updates on this repo.  We are planning to open source much much sooner than last year, but I can't give you a date.

**Comment by zeuscode** [comment]
i run this project , it come out Error:A problem was found with the configuration of task ':android:packageDebug'.
>XXXXXXX/debug.keystore' specified for property 'signingConfig.storeFile' does not exist.

**Comment by Bakeneko** [comment]
@zeuscode Wrong place and your error message is quite clear : you need to create a keystore file named debug.keystore

**Comment by nagendraksrivastava** [comment]
waiting for 2016 i/o app source , please release it

**Comment by c-ong** [comment]
This is best source code for Learn Android development, So I am waiting for.

**Comment by tasomaniac** [comment]
> much sooner
he said.

**Comment by specloli** [comment]
android Nougat has come . but this code do not . Sad story....

**Comment by minhoryang** [comment]
What about https://github.com/GoogleChrome/ioweb2016 ?

**Comment by QiiqeAzuara** [comment]
Android Studio 2.2 is available with 20+ new features. Meanwhile we continue to expect the source code ...

**Comment by AlirezaAkbarix** [comment]
My son is growing up and 2016 ver not committed

**Comment by cobblermaster** [comment]
Lets see if 2017 update will come before this; whats the problem?

**Comment by atetc** [comment]
Don't worry, guys! 
Our editorial team of AndroidResId (free channel in Telegram for Android developers  with more than 1k subscribers) is watching this repo every day and you will receive push notification about 2016 commit, if you are subscriber of our news channel https://telegram.me/AndroidResId.

**Comment by ExpensiveBelly** [comment]
What about decompiling the app and publish its source code in Github? I guess that's illegal?

**Comment by FarbodSalamat-Zadeh** [comment]
I originally didn't want to post on this thread as I don't want to be pestering, but I, along with many, many others have been waiting a long, long time for the source code to the 2016 I/O app.

I'm sure you're already aware that this is an extremely important resource for many developers, but I can't quite understand why it would be taking so long if you are "actively working on" publishing the source code for an app that was last updated on the Play Store in mid-May. I understand the need for code reviews, adding documentation, etc, but 5 months is a very long amount of time for this.

@PaulRashidi, you wrote that "we are planning to open source much much sooner than last year", but this doesn't seem to be the case as the 2015 commit was made at around this time last year.

My comment won't make a huge difference now, as the source code will inevitably be released soon, but for next year, on behalf of all developers using this repository as a resource, it would be wonderful to look forward to the source code being published within the first couple of months, at least.

**Comment by ArthurSav** [comment]
<img width="481" alt="screen shot 2016-10-14 at 11 09 15" src="https://cloud.githubusercontent.com/assets/2115575/19382044/c0bcaf64-91fe-11e6-9b9c-d381e03d2979.png">

**Comment by cobblermaster** [comment]
painful long wait

**Comment by cobblermaster** [comment]
another year has gone...

**Comment by jscorales** [comment]
2016 is coming to an end and no I/O 2016 source code yet

**Comment by amardeshbd** [comment]
We should look forward to 2017 😄 

Aside from joke, there are some great alternative apps to look after instead of waiting for this.
 - Plaid - https://github.com/nickbutcher/plaid
 - Android App Architecture - https://github.com/googlesamples/android-architecture
 - Firebase Android - https://github.com/firebase/quickstart-android
 - U2020 app using modern libraries - https://github.com/JakeWharton/u2020

Good luck 👍

**Comment by AlirezaAkbarix** [comment]
I think waiting for this source is useless because of changing the libs and techs!

e.g you'll notice that `appCompat` version is 21.0.3 or dagger 2 is in `beta` version :| 👎

**Comment by cobblermaster** [comment]
maybe its more promising to wait for io2017 source code...?

**Comment by PaulRashidi** [comment]
2016 code is available. Sorry for the wait.

**Comment by amardeshbd** [comment]
@PaulRashidi - the project title is updated to
> The Google I/O 2016 Android App https://play.google.com/store/apps/details?id=com.google.samples.apps.iosched

But the code is still old. There has been [no new commit](https://github.com/google/iosched/commits/master) containing the source code for 2016 app.

Did I miss something? 🤔

**Comment by QiiqeAzuara** [comment]
@amardeshbd Do not comment without having reviewed the code, Google IO 16 App implements location permission for Android 6, in addition to Material Design guidelines, such as RecyclerView, StateListAnimator, etc. Study the code, navigate the app and you will see that the code corresponds to this version.

**Comment by PaulRashidi** [comment]
@amardeshbd, you might be a little confused because we didn't squash the commits like we have in years past when open sourcing. The source code available will build an app very close to what launched at Google I/O 2016.

If you're curious: we continuously merged the commits in the main branch (that is published here) to another branch. In the other branch we customized the app a little bit more (mostly gradle.properties changes) for deployment to build and push to Google Play.

**Comment by ratulbside** [comment]
Readme says - "The source code in this repository reflects the app as of I/O **2015**."
