### ISSUE TITLE
Why not use android.support.design.widget.TabLayout?

### ISSUE THREAD

**Issue by ericntd** [google/iosched#203]
Why implementing SlidingTabLayout from scratch?

**Comment by PaulRashidi** [comment]
It could be switched out. When we publish the source shortly feel free to send along a PR.

**Comment by hzsweers** [comment]
> When we publish the source shortly feel free to send along a PR.

So...

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
