### ISSUE TITLE
Getting this error when trying to run app: "Gradle project sync failed... a valid App engine sdk was not found" 

### ISSUE THREAD

**Issue by jigar288** [google/iosched#204]
"Gradle project sync failed... Basic functionality (e.g editing,debugging) will not work properly" 
a valid App engine sdk was not found for module:server 
![screen shot 2016-08-21 at 5 29 22 pm](https://cloud.githubusercontent.com/assets/21162408/17840230/c3303896-67c5-11e6-9fec-390dca0620ad.png)

**Comment by 0x8BADFOOD** [comment]
Try to open clean project one more time and do not upgrade gradle just wait when sync for gradle will be finished. I just successfully build whole project but before had same erorr.

**Comment by PaulRashidi** [comment]
This should have been resolved, but please reopen if not.
