### ISSUE TITLE
Two years in a row of iosched source getting beat by the release of the OS it's supposed to serve as an example for.

### ISSUE THREAD

**Issue by hzsweers** [google/iosched#205]
This is kind of ridiculous.

**Comment by eneim** [comment]
I'm not always thumb up for an issue of this repo, accept for this one :D

**Comment by jimandreas** [comment]
I am finding that hacking away on the iosched 2015 vintage release to be really lot of fun and a lot of learning.   I am using its source for an experimental app that I am developing.   So no waiting around for the 2016 version for me.

For more information on the iosched app evolution - see Roman Nurik's blog - I just found this entry yesterday - and it gives you a better feel for how this app has developed over the years.

    http://roman.nurik.net/portfolio/

And on part of the iosched app architecture from Bruno Oliveira:

    http://android-developers.blogspot.de/2014/09/conference-data-sync-gcm-google-io.html

On sliding tabs:

    http://www.android4devs.com/2015/01/how-to-make-material-design-sliding-tabs.html

"Basically" there is a ton of stuff in the 2015 app to learn.   I am honestly not sure I will be ready to review the code for the 2016 app this year :-).

**Comment by PaulRashidi** [comment]
We've still got a few more things to address before we open source. Sorry for the delay.

**Comment by hzsweers** [comment]
That was basically the answer last year too, and it was finally released several months later with plans to "iterate from here". There has been no commit on master since that.
