### ISSUE TITLE
See picture - Error:A problem was found with the configuration of task ':android:packageDebug'. > File '/Users/jigarpatel/Downloads/iosched-master/android/debug.keystore' specified for property 'signingConfig.storeFile' does not exist.

### ISSUE THREAD

**Issue by jigar288** [google/iosched#208]
I am having an issue trying to build an apk. I am completely new to this. Please help.  
![screen shot 2016-09-02 at 9 58 34 pm](https://cloud.githubusercontent.com/assets/21162408/18222291/d38f6026-7158-11e6-8cff-95be17048c59.png)

**Comment by chweez** [comment]
You should have a file called 'debug.keystore' in 'C:\Users\jigarpatel\Downloads\iosched-master\android\' folder. If not, copy from 'C:\Users\jigarpatel\.android\debug.keystore'

**Comment by hashin** [comment]
If you don't want to sign your packages, just comment the following lines from build.gradle(Module:android):
`    signingConfigs {
        debug {
            storeFile file("../android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }`

It will compile.

**Comment by PaulRashidi** [comment]
We re-added the development keystore so the updated 2016 code doesn't have this issue.

**Comment by rschilling** [comment]
@PaulRashidi I'm seeing this issue today after updating Android Studio to 2.2.3. Can you please re-open this?

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
