### ISSUE TITLE
having issues with google play services

### ISSUE THREAD

**Issue by jfab2** [google/iosched#210]
I have updated my google play services and yet i'm still getting an error message that I should update Google play service run unless I update google play services, i'm using an infinix hot 2 phone, please help

**Comment by FarbodSalamat-Zadeh** [comment]
@jfab2 Is this still occurring? Are you only getting this error for this particular app (since other apps also use Google Play Services)?

You probably haven't updated Google Play services properly, but update this thread so we know if it's still an issue.

**Comment by PaulRashidi** [comment]
Sorry, we can't assist with Google Play services on this project, but it sounds like the Google Play services client library in the app that's creating that error or notification does require a new version than you have on your device.
