### ISSUE TITLE
text size of SlidingTabLayout is not changing

### ISSUE THREAD

**Issue by sench93** [google/iosched#211]
Text Size of tab titles are note changing no matter how much i give them SP-s.
![image](https://cloud.githubusercontent.com/assets/20376013/18960736/754dca40-8673-11e6-966a-0e12075b4ff2.png)
![image](https://cloud.githubusercontent.com/assets/20376013/18960779/91fa268e-8673-11e6-8d2f-9a25436962a2.png)

Any help please.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
