### ISSUE TITLE
Errors at compilation !

### ISSUE THREAD

**Issue by RegisAG** [google/iosched#212]
Hi,

I am a newbie with Android Studio. I donwloaded the project and tried to launch it.

I have fot the following errors:

> Conflict with dependency 'com.android.support.test.espresso:espresso-idling-resource'. Resolved versions for app (2.0) and test app (2.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
> 
> :android:prepareDebugAndroidTestDependencies FAILED
> :android:prepareDebugAndroidTestDependencies (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.008 secs.
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':android:prepareDebugAndroidTestDependencies'.
>   
>   > Dependency Error. See console for details.
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

Anybody can help ?

Thanks !

**Comment by kakinIA** [comment]
I have same same problem about that, how to solve?

**Comment by kakinIA** [comment]
i have same problem about that, how to solve?

**Comment by RegisAG** [comment]
Solution: in build.gradle, change "androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'" to "androidTestCompile 'com.android.support.test.espresso:espresso-core:2.0'" Hope this helps !

**Comment by PaulRashidi** [comment]
Shouldn't be present in 2016 code drop. Please re-open if it is.
