### ISSUE TITLE
how to customize Tab-layout view

### ISSUE THREAD

**Issue by rasik1010** [google/iosched#213]
can we make tab-layout like this image ?
please answer me if this is possible
Thank you
 
![tablayout42nite](https://cloud.githubusercontent.com/assets/22544243/20349869/4c6e3a62-ac32-11e6-9bfe-d1e2934a5e6d.PNG)

**Comment by yangyang1307027** [comment]
sure






At 2016-11-16 21:55:40, "rasik1010" <notifications@github.com> wrote:


can we make tab-layout like this image ?
please answer me if this is possible
Thank you

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
