### ISSUE TITLE
documentation nit - "installDebug" should be "installNormalDebug"

### ISSUE THREAD

**Issue by jimandreas** [google/iosched#214]
In the documentation step 8 (https://github.com/google/iosched/blob/master/doc/BUILDING.md) it calls for running

    ./gradlew installDebug

but this task doesn't exist - there are now various install targets - `installNormalDebug` and `installMapEditorDebug` among others.   It appears that if you just hit the Green Arrow in AS then you get a load of the Map Editor app.   The experience, if you haven't bothered (like me) to set up the Google Maps keys / auth, is a nice blank screen with a check box.  The fix is to open the Terminal (on Win7, maybe something else on Macs or Linux) and do a:

     gradlew installNormalDebug

(leave out the dot-slash on Win7 boxes) and you will get an install of the real iosched2016.   Thanks again to the team for posting the updated open source app!

**Comment by lazytes** [comment]
I agree.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
