### ISSUE TITLE
Xaumi Redmi Note 4

### ISSUE THREAD

**Issue by Dolguim** [google/iosched#224]
In gmail always apears the following message:

this app won't work properly unless you allow google play services request to access the contacts

![img_20170210_094111](https://cloud.githubusercontent.com/assets/25684784/22823755/edacfdf4-ef7c-11e6-8cc3-737227cb75d0.jpg)

**Comment by piotrek1543** [comment]
@Dolguim go to Settings, Apps/Applications, choose Gmail, then Permissions and finally change CheckBox state on Contacts item.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
