### ISSUE TITLE
This is the worst code base w/ instructions I've ever seen, embarassing. 

### ISSUE THREAD

**Issue by prettyponygirl** [google/iosched#226]
For this to work and build with EVERYTHING UPDATED IN ANDROID STUDIO, you MUST DELETED THE AndroidManifest.xml for MAPs. if you don't do this, the system will install "map editor" on your device only and you won't see anything inside the main app. Whoever maintains this repo is a moron. kys

**Comment by markmssd** [comment]
Well that's rude, feel welcome to open a PR fixing those issues or write clear instructions in README file instead, @prettyponygirl

**Comment by prettyponygirl** [comment]
no reason to not be rude, this is Google we're talking about, no room for stupid mistakes @markmssd

**Comment by intrepidkarthi** [comment]
Fix it and send a PR if you REALLY want to help others. Open source projects works this way regardless of who is behind.

**Comment by tasomaniac** [comment]
We don't have open source Android apps this big and widely used. Some open source small Google apps are being closed even (Google authenticator, clock, calculator etc) 
Unfortunately its harder to keep it open source and have fast release cycles. 
Google IO app is not one of them and it inspires developers all around the world. Of course it is not perfect. After all, these are humans developing it. The fact that they are working at Google doesn't change anything.

**Comment by piotrek1543** [comment]
@tasomaniac could you close this issue as irrevelant and rude.

**Comment by shgharib** [comment]
Just change build variant to normalDebug in android studio. @prettyponygirl

**Comment by tjohns** [comment]
@shgharib is correct. You need to set your build variant to normalDebug.

I also agree with the other comments here that the title/description for this is needlessly abrasive. Please keep issues constructive and polite.
