### ISSUE TITLE
Nav Drawer With Multiple Activities

### ISSUE THREAD

**Issue by ispam** [google/iosched#227]
Hello,

I am not sure if this is the right place to ask such thing but im intrigue by the way the Nav Drawer is implemented in this app. Does anyone care to explain the though process behind it? Thanks and sorry if not the right place to ask.

**Comment by elmargomez** [comment]
Yeah I am curious as well I hope somebody from the contributors will respond sooner.

**Comment by piotrek1543** [comment]
@ispam creating many activities is not good really idea. I suppose you're gonna write a simple app, so I would create one Activity (root view with Drawer) with multiple fragments. 

Read please first: https://developer.android.com/training/basics/fragments/fragment-ui.html

Create a DrawerActivity, which would be your root view and it would have only an implementation of side menu. Clicking on drawer menu item would launch a fragment.

This might be a nice example: https://github.com/chrisbanes/cheesesquare/pull/31/files

**Comment by elmargomez** [comment]
@piotrek1543 He is asking about the **iosched** implementation which does not use the traditional Single Nav - Multiple Fragment approach.

**Comment by piotrek1543** [comment]
@elmargomez sorry for misunderstanding ;-)

**Comment by ispam** [comment]
@piotrek1543  It's all good.

**Comment by ElyDantas** [comment]
Here's a example of app using activities instead of fragments https://github.com/ElyDantas/NavigationDrawer

**Comment by ispam** [comment]
@ElyDantas That's a nice implementation. I used what you did as base for my own, thank you.

**Comment by SamuelY** [comment]
How did you build it..., i have a fail like this
Error:(346, 5) error: method does not override or implement a method from a supertype
Error:(348, 29) error: cannot find symbol method setBatchPath(String)

The Error is occurred a file named Cms.java, and the code snipe of Cms.java as below:

    @Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }

could you help me to build this app? thanks

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
