### ISSUE TITLE
In the offline mode of the data, when entering the  SettingsActivity is not smooth.

### ISSUE THREAD

**Issue by xpbtmusic** [google/iosched#228]
Hello，
In the offline mode of the data, when entering the  SettingsActivity is not smooth.

**Comment by xpbtmusic** [comment]
[world_.trace.zip](https://github.com/google/iosched/files/887472/world_.trace.zip)

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
