### ISSUE TITLE
Release source code for I/O 2017 app

### ISSUE THREAD

**Issue by liujinchaoDS** [google/iosched#230]
I can't wait to enjoy it !

**Comment by vaibhavsingh97** [comment]
Same Question :smile:

**Comment by KoFuk** [comment]
I think so too

**Comment by im4eversmrt** [comment]
this should be interesting!!

**Comment by Ajimi** [comment]
We are waiting for google io 2017 release

**Comment by taany6210** [comment]
Good Question！

**Comment by kinshasa** [comment]
haha.

**Comment by Cordlesswire** [comment]
Waiting Line

**Comment by QiiqeAzuara** [comment]
until Google IO 18 xD

**Comment by tjohns** [comment]
Hi everyone! We're currently working on some post-event cleanup of our source code, but we're hoping to have it posted soon. Definitely sooner than I/O 2018. ;)

Stay tuned.

**Comment by vaibhavsingh97** [comment]
Thanks for the update @tjohns

**Comment by gpj008** [comment]
When is the code for I/O 2016 released?

**Comment by tjohns** [comment]
@gpj008: Source code for I/O 2016 was released back in 2016.

It was released a bit later than usual (November), but it won't be that long this year.

**Comment by danielmwai** [comment]
@tjohns any  update  on  2017  source  code release

**Comment by storytellerr** [comment]
i always loves to read code written by google developers. please release google i/o-17 code

**Comment by adrian110288** [comment]
#freeiosched17sourcecode

**Comment by tjohns** [comment]
@danielmwai: Soon. :)

**Comment by niravkhunt** [comment]
guys when #iosched17 will come ? Hope it is in Kotlin :)

**Comment by tjohns** [comment]
The 2017 source is now available under the '2017' tag in Git. 🎉 

https://android-developers.googleblog.com/2017/08/google-releases-source-for-google-io.html

Marking this issue as resolved. If you notice any issues with the 2017 release, please feel free to open a new issue.
