### ISSUE TITLE
Are kotlin PRs welcome ?

### ISSUE THREAD

**Issue by erluxman** [google/iosched#231]
I want to contribute by converting some code from Java to kotlin if there is a plan to migrate to kotlin.

**Comment by tjohns** [comment]
Thanks for asking.

We might migrate to Kotlin in a future version, but we haven't made that decision yet. (Kotlin was announced after the work for the 2017 app was completed.)

Accordingly, we aren't accepting Kotlin PRs... yet.

**Comment by zengalv** [comment]
Hhjkkkk
