### ISSUE TITLE
Message error in my xiaomi mi4c

### ISSUE THREAD

**Issue by nisfuf** [google/iosched#232]
![8054](https://user-images.githubusercontent.com/30151293/28170979-38c0d3da-6811-11e7-80e0-4e0564a64bdd.jpg)

why always appears this message after i reset my phone to reset factory? but i never installed google app ;(

**Comment by tjohns** [comment]
Sorry, but the issue you're reporting isn't related to this project (Google I/O Schedule app), and is off topic.

If you have more questions about this, you'll need to bring them up with your device's manufacturer or on the Android Google+ group.
