### ISSUE TITLE
setSelectedIndicatorColors not working

### ISSUE THREAD

**Issue by NinhvanLuyen** [google/iosched#234]
viewDataBinding.viewPager.setAdapter(pagerAdapter);
        viewDataBinding.viewPager.setOffscreenPageLimit(4);
        viewDataBinding.slidingTabs.setCustomTabView(R.layout.tab_mailbox, R.id.tabTitle,drawablesIds);
        viewDataBinding.slidingTabs.setDividerColors(getResources().getColor(R.color.Black_90));
        viewDataBinding.slidingTabs.setSelectedIndicatorColors(getResources().getColor(R.color.Black_90));
        viewDataBinding.slidingTabs.setDistributeEvenly(true);
        viewDataBinding.slidingTabs.setViewPager(viewDataBinding.viewPager);

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
