### ISSUE TITLE
apk build.gradle error - All flavors must belong to a named flavor dimension.

### ISSUE THREAD

**Issue by tombirmingham** [google/iosched#240]
Getting this error on build:

Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

**Comment by bernaferrari** [comment]
Use Android Studio 2.3.3 and they will disappear.

**Comment by felix-antony** [comment]
You might be facing this kind of issue when you upgrade to Android Studio 3.0.
Please refer this android developer page to resolve certain issues, and right configuration : https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

**Comment by AppleEducate** [comment]
Using Android Studio 3.0.1 and having the same issue

**Comment by GeethaLakha** [comment]
You can try by providing flavor dimensions for the productFlavors. It worked for me.
for ex: 
flavorDimensions "tier", "minApi"
    productFlavors{
        link1{
            dimension 'tier'
            ------------------------
        }
        link2{
            dimension 'minApi'
            ------------------------
        }
    }

**Comment by viral7chauhan** [comment]
Thanks @GeethaLakha

**Comment by jitendar7** [comment]
Thanks @GeethaLakha  , it worked for me

**Comment by zainyaseen** [comment]
Having the same problem, Please tell how to fix it. 

Thank you.

**Comment by Lemmynjash** [comment]
Having the same problem

**Comment by codeAndxv** [comment]
try  this,https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration#variant_aware

**Comment by balsikandar** [comment]
hi what tier and minApi represents

**Comment by soroda** [comment]
In which file please ? There's several "build.gradle"
In advance thanks

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
