### ISSUE TITLE
Execution failed for task ':server:appengineEndpointsGetClientLibs'

### ISSUE THREAD

**Issue by guanpj** [google/iosched#241]
### The error message was shown on Gradle Console like this when I run the app,  what's going on ?

:server:compileJava UP-TO-DATE
:server:processResources UP-TO-DATE
:server:classes UP-TO-DATE
:server:appengineEndpointsGetClientLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:appengineEndpointsGetClientLibs'.
> There was an error running endpoints command get-client-lib: connect timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.109 secs

**Comment by ngreedy** [comment]
same question

**Comment by snowjade** [comment]
same question

**Comment by snowjade** [comment]
same problem

**Comment by ITYDXTOCATTLE** [comment]
same problem

**Comment by majiag** [comment]
same question

**Comment by xns1001** [comment]
same question

**Comment by hpu-spring87** [comment]
same question

**Comment by jamin918** [comment]
same question

**Comment by conan5** [comment]
how to solve this?

**Comment by RoyXing** [comment]
same question

**Comment by snowjade** [comment]
It seems all the user commenting "same problem" come from China.

**Comment by small-dc** [comment]
same question

**Comment by easycold** [comment]
same question

**Comment by CoolerMe** [comment]
same question.

**Comment by KongDeli** [comment]
same question.

**Comment by ytp135** [comment]
same question.

**Comment by Oldbai** [comment]
same question.

**Comment by MrYangYang** [comment]
same question.

**Comment by jackhu222** [comment]
same question

**Comment by peppermintGum** [comment]
same question

**Comment by hym3991** [comment]
same question

**Comment by henrayluo** [comment]
same  question & come from China.

**Comment by faizalkassamalisc** [comment]
+1

**Comment by conghuahuadan** [comment]
same question

**Comment by tigerjiang** [comment]
+1

**Comment by tigerjiang** [comment]
Is anyone fix this issue? Thanks

**Comment by ZzzCy** [comment]
@Trevor Johns

**Comment by KongDeli** [comment]
Hi, I finally solved this. 
Read [this](https://stackoverflow.com/questions/47855552/google-iosched-sample-project-com-google-api-client-repackaged-com-google-comm/47856909#47856909)，and if you are in China, use SSTap or what so that you can get a global agent. Then all work.
参考链接中的答案按照他的步骤来，然后开着全局翻墙，让AndroidStudio走代理。就可以了。

**Comment by AbbyJM** [comment]
kongdeli的方法经测试可行，记得一定要挂代理

**Comment by CoolerMe** [comment]
我使用了多种方式,无论是Android studio代理,还是使用系统全局代理,都是那个问题.@ @kongdeli

**Comment by chenzhihui28** [comment]
开了全局之后重启一下android studio

**Comment by JayTaoNg** [comment]
我直接在Android Studio的设置中设置代理无效。在项目的gradle.properties文件设置代理才生效了，代理设置失败的可以试试我这种设置方式。

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
