### ISSUE TITLE
Execution failed for task ':server:compileEndpointsSrcJava'

### ISSUE THREAD

**Issue by Shiuend** [google/iosched#243]
**I have this problem when run the app, Can anyone can help me?**

:server:appengineEndpointsGetClientLibs UP-TO-DATE
:server:appengineEndpointsExpandClientLibs UP-TO-DATE
:server:compileEndpointsSrcJava

warning: [options] bootstrap class path not set in conjunction with -source 1.7
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\cms\Cms.java
	:346: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\cms\Cms.java
	:348: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\fcm\Fcm.java
	:393: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\fcm\Fcm.java
	:395: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\feedback\Feedback.java
	:264: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\feedback\Feedback.java
	:266: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\imagefeed\Imagefeed.java
	:290: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\iosched-master\server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\imagefeed\Imagefeed.java
	:292: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)

  ...<more>
16 errors
1 warning

 FAILED

FAILURE: Build failed with an exception.

**Comment by SamuelY** [comment]
I have the same problem

**Comment by diegoflassa** [comment]
Same problem here

**Comment by diegoflassa** [comment]
Found a quick fix:

In the file `iosched\server\build.gradle`, section `endpoints { ... }`, add the line `googleClientVersion = '1.23.0'`

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
