### ISSUE TITLE
build fail with error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by SamuelY** [google/iosched#244]
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/cms/Cms.java:346: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/cms/Cms.java:348: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/fcm/Fcm.java:393: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/fcm/Fcm.java:395: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/feedback/Feedback.java:264: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/feedback/Feedback.java:266: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/imagefeed/Imagefeed.java:290: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/imagefeed/Imagefeed.java:292: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/ping/Ping.java:576: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/ping/Ping.java:578: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/registration/Registration.java:312: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/registration/Registration.java:314: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/reservations/Reservations.java:262: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/reservations/Reservations.java:264: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/userdata/Userdata.java:1615: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/samuelyang/AndroidStudioProjects/iosched-master/server/build/generated-source/endpoints/java/com/google/samples/apps/iosched/rpc/userdata/Userdata.java:1617: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)

**Comment by SamuelY** [comment]
Could anyone tell me how to fix it? thanks

**Comment by SamuelY** [comment]
Error:(346, 5) error: method does not override or implement a method from a supertype
Error:(348, 29) error: cannot find symbol method setBatchPath(String)

The Error is occurred a file named Cms.java, and the code snipe of Cms.java as below:

    @Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }

could anyone help me to build this app? thanks

**Comment by ruanlei** [comment]
I have the same problem

**Comment by diegoflassa** [comment]
Found a quick fix:

In the file iosched\server\build.gradle, section endpoints { ... }, add the line googleClientVersion = '1.23.0'

**Comment by amilcar-andrade** [comment]
@diegoflassa thanks, your workaround works.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
