### ISSUE TITLE
Feed always scrolls up from bottom of list, even on orientation change

### ISSUE THREAD

**Issue by jeffmcnd** [google/iosched#245]
Every time I launch this app it does an insanely fast scroll animation to the top after starting at the bottom. Even when I've scrolled down the page to a list item, the page does not remember my scroll position, instead opting to show the bottom and perform the scroll up again on device rotation.

It looks as though the savedInstanceState is not being persisted throughout the Activity/Fragment lifecycle. This should be fixed in my mind.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
