### ISSUE TITLE
gradle compile fail 

### ISSUE THREAD

**Issue by devpopark** [google/iosched#246]
Error:Execution failed for task ':server:compileJava'.
> Compilation failed; see the compiler error output for details.

Error:(21, 63) error: package com.google.api.client.repackaged.com.google.common.base does not exist

**Comment by CoolMind** [comment]
Many errors in repository.
Also:

> error: method does not override or implement a method from a supertype
> error: cannot find symbol method setBatchPath(String)
> 

in many lines. Tips from https://stackoverflow.com/questions/46554771/cannot-find-symbol-method-setbatchpathstring-in-the-generated-source-from-ge didn't help.

**Comment by ViperAlpha** [comment]
There are other erros like Can't find Strings.isNullOrEmpty... and what CoolMind said..

**Comment by tigerjiang** [comment]
Is anyone fix this compile error?

**Comment by rafid059** [comment]
I have successfully compiled and ran the project. I've posted a solution on stackoverflow:

https://stackoverflow.com/a/47856909/2235972

**Comment by ViperAlpha** [comment]
@rafid059 solution worked perfectly. thanks.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
