### ISSUE TITLE
Error:Execution failed for task ':apk:processTargetSdk22NormalMapEditorDebugGoogleServices'. > File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by lizhenxin111** [google/iosched#249]
I build the project and it show :   
`Error:Execution failed for task :apk:processTargetSdk22NormalMapEditorDebugGoogleServices.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/lizhenxin/AndroidStudioProject/iosched-master/apk/src/targetSdk22NormalMapEditor/debug/google-services.json
  /home/lizhenxin/AndroidStudioProject/iosched-master/apk/src/debug/targetSdk22NormalMapEditor/google-services.json
  /home/lizhenxin/AndroidStudioProject/iosched-master/apk/src/targetSdk22NormalMapEditor/google-services.json
  /home/lizhenxin/AndroidStudioProject/iosched-master/apk/src/debug/google-services.json
  /home/lizhenxin/AndroidStudioProject/iosched-master/apk/google-services.json`

I have read the [Build instructions](https://github.com/google/iosched/blob/master/doc/BUILDING.md) in README.md, but I canot find the items in step 3(Tools > Android SDK Platform-tools - Tools > ............) . I only install the Google Play services in SDK Manager > SDK Tools but It is wrong yet.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.

**Comment by erlangp** [comment]
its fine https://github.com/google/iosched/blob/master/shared/google-services.json commited in version control?
