### ISSUE TITLE
unable to import from "server" module

### ISSUE THREAD

**Issue by smhasan11** [google/iosched#251]
```
import com.google.samples.apps.iosched.rpc.userdata.Userdata;
import com.google.samples.apps.iosched.rpc.userdata.model.UserData;

class UserDataSyncHelper extends AbstractUserDataSyncHelper {
```

In the above class, those 2 imports showing error. Though I see those classes are in 

> \server\build\generated-source\endpoints\java\com\google\samples\apps\iosched\rpc\userdata\Userdata.java

in "lib" build.gradle:
```
dependencies {
    // Backend server
    compile project(path: ':server', configuration: 'android-endpoints')
```

BTW, I'm trying to create a separate project from the scratch by using the same code-base.
I can't find anything which is causing this error.

Please help.
Thanks,

**Comment by smhasan11** [comment]
@amardeshbd, @AjkP, @eyecatchup , @yelinaung , @romannurik , @tjohns , @freewheelnat, @btco, @PaulRashidi, @nageshs 
can anyone please help me.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
