### ISSUE TITLE
Unable to build App in Android Studio 3.0

### ISSUE THREAD

**Issue by bbincybbaby** [google/iosched#252]
I tried to build this repository in Android Studio 3.0, but getting lot of build errors. When will this source will updated ?

**Comment by rafid059** [comment]
What are the errors? Have you looked in #246?

**Comment by YeForCoding** [comment]
it's Jesus.  I spent a whole day to build this project in Android studio 3.1. I solved the build errors one by one ,but failure after failure ... ... the failure makes my crazy ...    please release the IO18 asap .. and please make sure it runs well in Android studio 3.1 ..

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
