### ISSUE TITLE
There was an error running endpoints command get-client-lib: connect timed out

### ISSUE THREAD

**Issue by IurKwan** [google/iosched#253]
I was able to visit Google but compiled overtime

This is the wrong message

Error:Execution failed for task ':server:appengineEndpointsGetClientLibs'.
> There was an error running endpoints command get-client-lib: connect timed out

**Comment by kinshasa** [comment]
same to you.

**Comment by rafid059** [comment]
#241 has the solution

**Comment by zhuzhihui** [comment]
same to you.

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
