### ISSUE TITLE
Wrong language being shown

### ISSUE THREAD

**Issue by tererecool** [google/iosched#254]
I tried the app on, as today, the latest nexus 7 API 27 emulator where I set 3 languages: 1. netherland, 2. german, 3. english. The app is shown in english now, also after killing and starting it again, is this the expected behavior? should not the fallback be german as it is defined in the system settings as the second language? Your app has german strings.
I tested this because we also have a problem with our app with this environment, some strings are shown in english and others in german, when I restart my own app the german strings are loaded this time, but in your case german is not loaded at all :S

**Comment by JoseAlcerreca** [comment]
Obsolete after the 2018 version rewrite.
