### ISSUE TITLE
Release source code for Google I/O 2018 app

### ISSUE THREAD

**Issue by KamranMackey** [google/iosched#255]
The I/O 2017 source code was published last year, so it'd be awesome if the 2018 app source code could be released too. :)

**Comment by atharvaunde59** [comment]
yes we are looking for I/O 2018 code as it is based on Material Design 2.0 😍

**Comment by tjohns** [comment]
We'll be releasing the 2018 source code shortly after I/O 2018 concludes. Stay tuned.

**Comment by KamranMackey** [comment]
@tjohns That's awesome! Thanks for the update :)

**Comment by iz-ben** [comment]
Waiting :)

**Comment by AnupamSingh0211** [comment]
Eagerly waiting

**Comment by yallam08** [comment]
Still not released?! come on guys, just hit push :D

**Comment by zerofate** [comment]
Waiting

**Comment by rahulraopune** [comment]
Waiting for some material design and Android jetpack action....

**Comment by saurabhkpatel** [comment]
Does Google have any plan to release it?

**Comment by aliumujib** [comment]
Come on .... Waiting on you peeeople

**Comment by shailen** [comment]
We will be open sourcing it soon. Thank you for your patience.

**Comment by YeForCoding** [comment]
Before release, please make sure it works well with Android studio 3.1,   thanks so much !!!!

**Comment by Aroniez** [comment]
Now would be a good time to release, even my grandma agrees.

**Comment by zakirhusain** [comment]
I think they are going to launch on WWDC 2018 event.

**Comment by mspmax** [comment]
I Just woke up from a coma... is it released yet?

**Comment by Nyconing** [comment]
MD2.0 use too much proprietary resources.
I think they wont be releasing it before make them open source.

**Comment by JayTaoNg** [comment]
Waiting

**Comment by AlexeyZubkovskiy** [comment]
I'm waiting for you, Google guys. Lets push!

**Comment by enriquebautista** [comment]
one debt to society later ...

**Comment by davidamey** [comment]
Nearly time to start an issue for the 2019 code...

**Comment by willbe058** [comment]
waaaaaaaiting...

**Comment by KamranMackey** [comment]
The minimum time it'll be released guys is August, similar to last year, when the 2017 app was open-sourced in August as well. So yeah, minimum is August. Could be earlier, could be later, but that's a rough estimate.

**Comment by Shamus-Murray-ck** [comment]
Is Google using `Standard Bottom Sheets`, `Model Bottom Sheets`, or `Backdrop` for their filter pane in the I/O 2018 app? I would love to see their implementation for it.

**Comment by Nevall** [comment]
waaaaaaaiting...

**Comment by HHdl** [comment]
When is open source

**Comment by sawyerhard** [comment]
waiting...

**Comment by forevervivi** [comment]
waaaaaaaiting...

**Comment by clucle** [comment]
waiting....

**Comment by Advice-Dog** [comment]
Spamming their GitHub with useless comments will not make them release it any faster.

**Comment by atharvaunde59** [comment]
@shailen  come on now Android P is out ! at lease release the sources now!!

**Comment by edipo2s** [comment]
Why take so long to release sources of an app already published?

**Comment by KamranMackey** [comment]
You guys have to stop asking for them to release the source code. It'll be released whenever it gets released.

But @shailen do you happen to have any updates to share on the matter?

**Comment by toktogul** [comment]
they are rewriting it to kotlin native

**Comment by shailen** [comment]
Thanks for your patience. We've just pushed the 2018 code.
