### ISSUE TITLE
iphone 5

### ISSUE THREAD

**Issue by vinny12343** [google/iosched#263]
how to change iOS

**Comment by vinny12343** [comment]
changing iOS

**Comment by Kisty** [comment]
Hi @vinny12343. I can see how you got confused as the project starts with 'ios' in **ios**ched. This is an Android app and as far as I'm aware, you can't run an Android app on iOS. 

There is, however an iOS app which you can download is here: https://itunes.apple.com/us/app/google-i-o/id1109898820?mt=8 and the source code is here: https://github.com/google/iosched-ios. Hope this helps.

**Comment by AlbertJQarK** [comment]
Sorry but @vinny12343 dont even know his own email, I'm not related with
his problem and this is not his email.

Thanks and I hope you will find him.

**Comment by Kisty** [comment]
@AlbertJQarK just got back from support. It's not that the OP has your email, not at all. You're watching this repository so you get all the issues and pull requests etc. 

If you don't want all this, then please change your preferences or contact support@github.com for more help. Hope this helps!
