### ISSUE TITLE
Release source code for Google I/O 2019 app

### ISSUE THREAD

**Issue by YuriPopiv** [google/iosched#309]
When the 2019 source code will be released?)

**Comment by amardeshbd** [comment]
@YuriPopiv I think the issue can be closed as the source code is now available 🙌 

Source
* https://android-developers.googleblog.com/2019/08/google-releases-source-code-for-google.html
* PR - Push the code for 2019 @ https://github.com/google/iosched/pull/318

> 2019 Release Date: Aug 14th, 2019 ~96 days after I/O 19
