### ISSUE TITLE
viewLifecycleOwner in DialogFragment never initialized

### ISSUE THREAD

**Issue by IonutNegru87** [google/iosched#343]
I noticed the `ThemeSettingDialogFragment` does not use the `viewLifecycleOwner`, but the reference to itself.
The recommendations show that we should use the Fragment `viewLifecycleOwner`, but this will never be initialized because of how the DialogFragment is created, through `onCreateDialog()` method.

I do not know if this is a bug in the **Fragments** or in the **Lifecycle** dependency, but I failed to update this to work correctly.

**Comment by ZhuSniffsTheRose** [comment]
you can find more from [DialogFragment lifecycle](https://developer.android.com/guide/fragments/dialogs#lifecycle)

**Comment by IonutNegru87** [comment]
Closing this as it seems that the documentation covers that case. Seems to be more a lint issue not properly detecting the owner.
