### ISSUE TITLE
Not able to build project in Android Studio Arctic Fox 2020.3.1. beta 2

### ISSUE THREAD

**Issue by mistrydarshan99** [google/iosched#370]
When I opend the project in Android Studio Arctic Fox 2020.3.1. beta 2 it gives me prompt to forcefully update gradle.

Here I attach scrrenshot of Android Studio configuration.

<img width="699" alt="Screenshot 2021-05-26 at 5 22 13 PM" src="https://user-images.githubusercontent.com/5453894/119655694-8055e380-be47-11eb-9983-dbd06450ffae.png">

Screenshot of prompt to update gradle file

After upgrading gradle 7.0.0-beta02 not able to buid project.

<img width="549" alt="Screenshot 2021-05-26 at 5 27 42 PM" src="https://user-images.githubusercontent.com/5453894/119655965-c612ac00-be47-11eb-875f-a22b517cda38.png">

<img width="584" alt="Screenshot 2021-05-26 at 5 27 57 PM" src="https://user-images.githubusercontent.com/5453894/119655990-cd39ba00-be47-11eb-8bfe-dba0283bb50a.png">

`classpath("com.android.tools.build:gradle:7.0.0-beta02")`

Attached screenshot of Error:

<img width="1336" alt="Screenshot 2021-05-26 at 5 29 36 PM" src="https://user-images.githubusercontent.com/5453894/119656148-feb28580-be47-11eb-9586-e2a005de27de.png">

<img width="1348" alt="Screenshot 2021-05-26 at 5 29 47 PM" src="https://user-images.githubusercontent.com/5453894/119656180-08d48400-be48-11eb-921a-a8af4e025772.png">

**Comment by JoseAlcerreca** [comment]
Yeah Studio beta/canary is now picky when it comes to AGP and gradle versions.

@wojtek-kalicinski has migrated it to beta03 in #373
