### ISSUE TITLE
build failed(Android Studio (Beta) 0.8.6)

### ISSUE THREAD

**Issue by linghp** [google/iosched#40]
Error:A problem was found with the configuration of task ':android:packageClassicDebug'.

> File 'E:\others\iosched-master\android\debug.keystore' specified for property 'signingConfig.storeFile' does not exist.
> help!!!

**Comment by yipinghuo** [comment]
i  meet the same problem as linghp,then i download the code again,but the problem is exits yet,help !!!thanks!

**Comment by peter-budo** [comment]
@yipinghuo time to read instructions https://github.com/google/iosched/blob/master/doc/BUILDING.md
