### ISSUE TITLE
ScrollView inside Navigation Drawer Lag

### ISSUE THREAD

**Issue by ardok** [google/iosched#49]
Tried installing this on a Galaxy Nexus running IceCreamSandwichMR2

Kernel:
3.0.8-ge28757d
android-build@apa28 # 1

Build:
yakju-userdebug IceCreamSandwichMR2

I believe it's stock.

Anyway, I tried adding more items into the navigation drawer following iosched app (under BaseActivity.java, inside `populateNavDrawer` method, just add more stuff into `mNavDrawerItems`).
The ScrollView is barely scrollable. I just added more `NAVDRAWER_ITEM_SETTINGS`, like 10 times, and as I scroll through the ScrollView, it keeps stuttering. The scroll just stops and I have to lift my finger up and do it again only to move the scroll a tiny bit and repeat.

Tried it on my Nexus 5 (running latest Android all stock), the problem doesn't seem to appear.
Is it more of hardware problem or Android version?
Is it better to create Navigation Drawer using ListView instead of what this app (iosched) does?

Thanks.

P.S. uploaded a video: https://www.youtube.com/watch?v=cmFkFDvEoKU&feature=youtu.be
Should be unlisted.

**Comment by burntapples** [comment]
I'm having this same issue on my HTC one m8. Did you figure out the problem?

**Comment by JoseAlcerreca** [comment]
Obsolete
