### ISSUE TITLE
GCMBaseIntentService is deprecated

### ISSUE THREAD

**Issue by labtopia** [google/iosched#51]
android/src/main/java/com/google/samples/apps/iosched/gcm/GCMIntentService.java

The GCM portion of the I/O sample is implemented using a demo client library that is deprecated:

http://developer.android.com/reference/com/google/android/gcm/GCMBaseIntentService.html

These "helper libraries" were always intended as a demo; they've never been an official, supported API. 

We want people to use the official GMS Core API now:

http://developer.android.com/reference/com/google/android/gms/gcm/GoogleCloudMessaging.html

Unfortunately, this recent blog post (Sept. 2014) gives additional visibility to the deprecated demo API:

http://android-developers.blogspot.com/2014/09/conference-data-sync-gcm-google-io.html

We should update this implementation.

**Comment by JoseAlcerreca** [comment]
Obsolete
