### ISSUE TITLE
Sessions feedback feature

### ISSUE THREAD

**Issue by AlexKorovyansky** [google/iosched#58]
Any ideas how to customize the app keeping feedback feature?

As I can see you are using EventPoint API for session feedback feature. 
Is it free or paid service? And what about creating app engine app for handling sessions feedback?

**Comment by AhmadElMelegy** [comment]
If you had found an answer please let me know

**Comment by PaulRashidi** [comment]
The 2015 source has a todo where you have access to the questions and answers and can send it to a backend server of your choice. This isn't implemented in the current source code's backend server, but it could be. If you're interested in adding such a feature to the backend let me know.
