### ISSUE TITLE
Extra comma found in DEFAULT_SORT of FeedBack class

### ISSUE THREAD

**Issue by WKnak** [google/iosched#73]
file ScheduleContract.java

can this extra comma cause problems?

public static class Feedback implements BaseColumns, FeedbackColumns, SyncColumns {
...
/*\* Default "ORDER BY" clause. */
public static final String DEFAULT_SORT = BaseColumns._ID + " ASC, ";
...
}

**Comment by PaulRashidi** [comment]
Thanks, this got cleaned up.
