### ISSUE TITLE
Wearables project's Util.LOGD accidentally recursive

### ISSUE THREAD

**Issue by DamianMehers** [google/iosched#75]
In the Wearables project, the Utils.LOGD method calls itself, whereas it should call Log.d?

    public static final void LOGD(String TAG, String message) {
        if (Log.isLoggable(TAG, Log.DEBUG)) {
            LOGD(TAG, message);
        }
    }

**Comment by tjohns** [comment]
This was recently fixed by @romannurik in commit ba58a98.
