### ISSUE TITLE
Bug in LoginAndAuthHelper.java, onActivityResult()

### ISSUE THREAD

**Issue by Alchete** [google/iosched#76]
Hi Roman,

First, thank you and your fellow teammembers for posting this great example.

I've been trying to use the LoginAndAuthHelper class and noticed what appears to be a bug --

The code will never enter the second check for requestCode == REQUEST_RECOVER_FROM_PLAY_SERVICES_ERROR, since it's nested inside the first IF check.

I think you want another OR clause in the first check.

    /** Handles an Activity result. Call this from your Activity's onActivityResult(). */
    public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        Activity activity = getActivity("onActivityResult()");
        if (activity == null) {
            return false;
        }

        if (requestCode == REQUEST_AUTHENTICATE ||
                requestCode == REQUEST_RECOVER_FROM_AUTH_ERROR ||
                requestCode == REQUEST_PLAY_SERVICES_ERROR_DIALOG) {

            LOGD(TAG, "onActivityResult, req=" + requestCode + ", result=" + resultCode);
            if (requestCode == REQUEST_RECOVER_FROM_PLAY_SERVICES_ERROR) {
                mResolving = false;
            }
.
.
.

**Comment by PaulRashidi** [comment]
I think this was resolved in the 2015 source. Please re-open if you don't think so.
