### ISSUE TITLE
Critical - Crash on some Samsung devices with android 4.2.2

### ISSUE THREAD

**Issue by vandzi** [google/iosched#79]
App will always crash on some Samsung devices with android 4.2.2. Replicated on Samsung Galaxy Light model SGH-T399. You can replicate it using https://appthwack.com/devicelab
It's critical because all apps which user appcompat v21 toolbar will crash on these devices.

Stacktrace:
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:620) at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:823) at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:815) at android.support.v7.internal.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:554) at android.support.v7.internal.app.ToolbarActionBar.setListMenuPresenter(ToolbarActionBar.java:558) at android.support.v7.app.ActionBarActivityDelegateBase.setSupportActionBar(ActionBarActivityDelegateBase.java:178) at android.support.v7.app.ActionBarActivity.setSupportActionBar(ActionBarActivity.java:92) at com.google.samples.apps.iosched.ui.BaseActivity.getActionBarToolbar(BaseActivity.java:1253) at com.google.samples.apps.iosched.ui.BaseActivity.setContentView(BaseActivity.java:423) at com.google.samples.apps.iosched.ui.BrowseSessionsActivity.onCreate(BrowseSessionsActivity.java:92) at android.app.Activity.performCreate(Activity.java:5326) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2304) at android.app.ActivityThread.access$700(ActivityThread.java:152) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:176) at android.app.ActivityThread.main(ActivityThread.java:5299) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) at dalvik.system.NativeStart.main(Native Method)

**Comment by ravibhan90** [comment]
If anyone interested in using a solution without progaurd . Read the [link][1] i have tried this in one of my apps which gave the exception on setSupportActionBar(toolbar) in onCreate().

Its pretty simple just add try catch block around the call

  try {
        setSupportActionBar(toolbar);
    } catch (Throwable t) {
        // WTF SAMSUNG!
    }

  [1]: https://www.reddit.com/r/androiddev/comments/2lluck/appcompatv7_v2100_causing_crash_on_samsung/clwd14p

**Comment by AndroidDeveloperLB** [comment]
Accroding to the last posts of the bug-report, this should be fixed on the new version of the support library (24) :
https://code.google.com/p/android/issues/detail?id=78377#c374

Someone even claimed it fixed it.

**Comment by SamuelY** [comment]
How did you build it..., i have a fail like this
Error:(346, 5) error: method does not override or implement a method from a supertype
Error:(348, 29) error: cannot find symbol method setBatchPath(String)

The Error is occurred a file named Cms.java, and the code snipe of Cms.java as below:

    @Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }

could you help me to build this app? thanks

**Comment by JoseAlcerreca** [comment]
Obsolete
