### ISSUE TITLE
"Cursor finalized without prior close()" warning

### ISSUE THREAD

**Issue by pmarino** [google/iosched#81]
Hello! First of all, thanks so much for an incredible project! I recently noticed that every so often during syncing and configuration changes, there will be a "Cursor finalized without prior close()" warning. It seems like the cursor doesn't always get closed in the "loadHashcodes" method for SpeakersHandler, VideosHandler, and ExpertsHandler.

![cursor_warning](https://cloud.githubusercontent.com/assets/5267374/4910328/3577d758-647e-11e4-972c-51a924995924.jpg)

**Comment by PaulRashidi** [comment]
I'm pretty sure we took care of a few non-closed cursors in the 2015 source release. Please re-open if this re-occurs.
