### ISSUE TITLE
Can't sync with Google+ profile data

### ISSUE THREAD

**Issue by jrodbx** [google/iosched#83]
I'm noticing that my Google Plus image and name are not showing up in the navigation drawer, but it used to.

Checking logcat, I see: Unexpected response code 403 for https://www.googleapis.com/plus/v1/people/me

Did a G+ scope change?  Any ideas?

Sample stack trace:
11-05 01:45:46.365     990-2394/? E/Volley﹕ [93] a.a: Unexpected response code 403 for https://www.googleapis.com/plus/v1/people/me
11-05 01:45:46.365  24350-24350/PACKAGE D/iosched_LoginAndAuthHe﹕ Helper connected, account ACCOUNT_NAME
11-05 01:45:46.365  24350-24350/PACKAGE D/iosched_LoginAndAuthHe﹕ We don't have Google+ info for ACCOUNT_NAME yet, so loading.
11-05 01:45:46.365  24350-24350/PACKAGE D/iosched_LoginAndAuthHe﹕ No need for auth token, we already have it.
11-05 01:45:46.365  24350-24350/PACKAGE D/iosched_LoginAndAuthHe﹕ Auth success for account ACCOUNT_NAME, newlyAuthenticated=false
11-05 01:45:46.365  24350-24350/PACKAGE D/iosched_BaseActivity﹕ onAuthSuccess, account ACCOUNT_NAME, newlyAuthenticated=false
11-05 01:45:46.365  24350-24350/PACKAGE D/iosched_BaseActivity﹕ Refreshing MySchedule data
11-05 01:45:46.405  24350-24350/PACKAGE D/iosched_GCMs﹕ GCM registration is valid and for the correct gcm key: b32e........27e9
11-05 01:45:46.405  24350-24350/PACKAGE I/iosched_BaseActivity﹕ Already registered on the GCM server with right GCM key.
11-05 01:45:46.515  24350-24350/PACKAGE D/iosched_LoginAndAuthHe﹕ onPeopleLoaded, status=Status{statusCode=NETWORK_ERROR, resolution=null}
11-05 01:45:46.515  24350-24350/PACKAGE E/iosched_LoginAndAuthHe﹕ Failed to load plus proflie, error 7

**Comment by Proximator** [comment]
You should just copy the keystore file from $HOME/.android/debug.keystore into android project and replace the existing debug.keystore (see in build.gradle of android module)
 signingConfigs {
        debug {
            storeFile file("../android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            storeFile file("../android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

**Comment by PaulRashidi** [comment]
Could you confirm whether this is still an issue in 2015 source?
