### ISSUE TITLE
deleteDatabase not working under Lollipop

### ISSUE THREAD

**Issue by 5TFN** [google/iosched#91]
I think this call is actually never made in the current iosched version, but since I am using the same method in another app and ran into this issue I tried to make the same call in the iosched app.

``` java
context.getContentResolver().delete(ScheduleContract.BASE_CONTENT_URI, null, null);
```

this works in pre API 21 but results in this under Lollipop:

```
11-12 16:33:52.187    2312-2312/com.google.samples.apps.iosched D/iosched_ScheduleProvid﹕ delete(uri=content://com.google.samples.apps.iosched, account=*****@gmail.com)
11-12 16:33:52.187    2312-2312/com.google.samples.apps.iosched D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
11-12 16:33:52.188    2312-2312/com.google.samples.apps.iosched E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.samples.apps.iosched, PID: 2312
    java.lang.UnsupportedOperationException: Unknown uri for -1: content://com.google.samples.apps.iosched
            at com.google.samples.apps.iosched.provider.ScheduleProvider.buildSimpleSelection(ScheduleProvider.java:749)
            at com.google.samples.apps.iosched.provider.ScheduleProvider.delete(ScheduleProvider.java:555)
            at android.content.ContentProvider$Transport.delete(ContentProvider.java:309)
            at android.content.ContentResolver.delete(ContentResolver.java:1299)
```

it looks like the uri parsing is causing the issue.
The passed uri is "content://com.google.samples.apps.iosched" which is exactly the ScheduleContract.BASE_CONTENT_URI but the statement to delete the database is never reached in the ScheduleProviders delete method.

``` java
    @Override
    public int delete(Uri uri, String selection, String[] selectionArgs) {
        String accountName = getCurrentAccountName(uri, false);
        LOGV(TAG, "delete(uri=" + uri + ", account=" + accountName + ")");
        if (uri == ScheduleContract.BASE_CONTENT_URI) {
            // Handle whole database deletes (e.g. when signing out)
            deleteDatabase();
            notifyChange(uri);
            return 1;
        }
```

**Comment by SamuelY** [comment]
How did you build it..., i have a fail like this
Error:(346, 5) error: method does not override or implement a method from a supertype
Error:(348, 29) error: cannot find symbol method setBatchPath(String)

The Error is occurred a file named Cms.java, and the code snipe of Cms.java as below:

    @Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }

could you help me to build this app? thanks

**Comment by JoseAlcerreca** [comment]
Obsolete
