### ISSUE TITLE
Issue: CI configuration and gradle-wrapper.jar files need be fixed/updated

### ISSUE THREAD

**Issue by ardock** [google/iosched#94]
CI builds are failing due "device not found" or "code 137" errors and the project includes an outdated gradle-wrapper.jar version 1.6 (current version is 2.2.1).

The wrapper is used to test contributions and I'm worried about the changes included in new versions.

If a project member updates the binary we all could use the same version locally and using CI server.

![wrapper changes 1 2014-12-11 09 06 13](https://cloud.githubusercontent.com/assets/1142360/5392217/28df0f08-8124-11e4-9ae6-c50a610b4714.png)

![wrapper changes 2 2014-12-11 09 05 33](https://cloud.githubusercontent.com/assets/1142360/5392221/2f50defc-8124-11e4-82da-daf9eb4b0a4d.png)

One option is to add a gradle task to the project build file or execute the task on CI builds.
http://www.gradle.org/docs/current/userguide/gradle_wrapper.html

**Comment by piotrek1543** [comment]
@ardock what is that application you use on Ubuntu to git diff? Could you give a its name?

**Comment by ardock** [comment]
@piotrek1543 I selected the file and pressed control+D, **compare with** menu option, using Android Studio.

**Comment by piotrek1543** [comment]
@ardock, thanks.
