### ISSUE TITLE
Changing TimeZone in the app

### ISSUE THREAD

**Issue by nikhilgupta280695** [google/iosched#97]
Hi, I tried to change the TimeZone of the app using the the following line in "config.java" file.

public static final TimeZone CONFERENCE_TIMEZONE = TimeZone.getTimeZone("Asia/Kolkata");

It doesn't seem to be the only manipulation.
Can someone tell, what else needs to be done to change it ?

**Comment by anuragdake** [comment]
Try using `Asia/Calcutta` as time zone id.

The zone used to be called `Asia/Calcutta` and was renamed to `Asia/Kolkata`, but there is still an alias in the tzdb that points the old name to the new one.
[Check This out](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
